### PR TITLE
Feature/conda recipe

### PR DESCRIPTION
**Pull request by pdiercks**
Hi, this PR adds a recipe to build a conda package which is then done automatically in the github actions. 
If everything works as expected the package might be uploaded to my channel for now.

### CODE REVIEW

**Comment by pdiercks** [comment]
I added a secret ANACONDA_TOKEN to both repositories (BAMResearch/fenics_helpers and my fork pdiercks/fenics_helpers). The build of the package is successful, but for some reason the upload in case of the pipeline running here fails since the token seems to be empty. If I try to merge into the master branch of my fork it works as expected. (see [here](https://github.com/pdiercks/fenics_helpers/runs/6256605524?check_suite_focus=true))
From my current understanding it should work if the secret is defined in both repositories (maybe the upload won't fail anymore once this is merged ...). 
Do you have any comments on this PR @TTitscher , @Psirus ?

**Review by TTitscher — APPROVED** [review]
First, thanks for updating the outdated `setup.py` :)

As you may know, I rarely work with conda and, honestly, do not (yet?) see a benefit in a pure python project. Anyways, as this PR does not modify the existing code, I am completely fine with the changes! 

Maybe you could mention the installation via conda in README.md.

**Comment by pdiercks** [comment]
> As you may know, I rarely work with conda and, honestly, do not (yet?) see a benefit in a pure python project

I also do not have a strong argument in this case. I guess it just makes it a bit conda friendlier instead of using pip inside the conda environment. 
If its available from some conda channel then fenics helpers could also be easier included as a dependency in another build, e.g. for fenics-constitutive.

**Comment by joergfunger** [comment]
IMO, many of the workflow tools provide features to define a compute environment either using conda or docker (pure pyton packages using e.g. pip are usually not supported). In addition, integrating a package (e.g. this one) into other conda packages via pip might work, though it is not fully ensured that all the dependencies are correctly resolved. Thus, having both a python module and a conda package is of advantage, though I agree that for a pure python user this is not a must. What is hany about conda is that you can also define the python version (that does not have to be the same as the ones installed in your system).

**Pull request merged**
